library(combinat)
library(dHSIC)
library(kernlab)
library(mgcv)
library(mboost)
library(pcalg)
library(RBGL)
library(tree)

source("MCC.R")
source("treeANM.R")
source("dataGeneration.R")

source("dependencies/CAM/R/CAM.R")
source("dependencies/CAM/R/computeScoreMat.R")
source("dependencies/CAM/R/computeScoreMatParallel.R")
source("dependencies/CAM/R/pruning.R")
source("dependencies/CAM/R/selGam.R")
source("dependencies/CAM/R/selGamBoost.R")
source("dependencies/CAM/R/train_gam.R")
source("dependencies/CAM/R/train_GAMboost.R")
source("dependencies/CAM/R/updateScoreMat.R")

source("dependencies/codeANM/code/fitting/fitting.R")
source("dependencies/codeANM/code/inferDAG/ICML.R")
source("dependencies/codeANM/code/indtests/indtestAll.R")
source("dependencies/codeANM/code/indtests/indtestHsic.R")

source("dependencies/SID/R/computePathMatrix.R")
source("dependencies/SID/R/computePathMatrix2.R")
source("dependencies/SID/R/dSepAdji.R")
source("dependencies/SID/R/structIntervDist.R")
